apiVersion: apps/v1
kind: Deployment
metadata:
  name: IMAGE_NAME-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: api-IMAGE_NAME
      env: production
  template: 
    metadata:
      name: webapp
      labels:
        role: api-IMAGE_NAME
        env: production
    spec:
      containers:
        - name: IMAGE_NAME
          image: gcr.io/PROJECT_ID/IMAGE_NAME:VERSION
          imagePullPolicy: Always
          ports:
          - containerPort: 5050
      imagePullSecrets:
      - name: gcr-json-key
      
